//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        public int CategoryId { get; set; }
        public int HostId { get; set; }
        public string Ip { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
